### ISSUE TITLE
Issue with hiresfix

### ISSUE THREAD

**Issue by saltacc** [sALTaccount/VAE-BlessUp#1]
img2img and hiresfix use the encoder block of the VAE. Possible apply the inverse operation to the first layer of the encoder? Will need to do testing

**Comment by catboxanon** [comment]
Was just about to open this issue, the VAE provided here in this repo and the on-the-fly modification via [this extension](https://git.mmaker.moe/mmaker/sd-webui-vae-blessup) have the same problem.

**Comment by saltacc** [comment]
Fixed the problem, will update this repo and make a PR on the extension soon
Left is with the fix and right is without
No hiresfix
![image](https://user-images.githubusercontent.com/18043686/223574600-8270439f-c759-4bdc-8387-5022ed5acf61.png)
R-ESRGAN 4x+ Anime6B hires upscaler
![image](https://user-images.githubusercontent.com/18043686/223574628-c1cfc650-3735-449f-9f0f-55b23c48c8fd.png)
Notice how the old (right) loses contrast again from passing through the VAE. However, by implying the inverse operation to the VAEs encoder, we can preserve the contrast.

**Comment by saltacc** [comment]
However, this method isn't perfect. We are actually modifying the latents themselves this way. This can cause the images to not look as good. However, the effect shouldn't be noticable because we are going to add a ton of noise to the latents anyways. Note that this will not affect anything besides hiresfix and img2img.
![image](https://user-images.githubusercontent.com/18043686/223576762-58853a06-efbe-4cf1-98d8-f1333dd88738.png)
Just passing the image into the VAE and back out destroys a bit of quality. However, I don't see any use just passing images through a VAE, generally they are being used with denoising as well, so the quality difference shouldn't make a noticeable impact.

**Comment by saltacc** [comment]
https://github.com/sALTaccount/VAE-BlessUp/commit/901498cfb0bd17e5cf090cfa49f36edfd8a7f4a7

**Comment by catboxanon** [comment]
Isn't brightness now applying the same operation as contrast? `bias` is only mentioned in the comment and not actually used in the code now. Actually it looks like the brightness code is copied from contrast verbatim, including variables.

**Comment by saltacc** [comment]
yeah.......... just fixed that :sweat:
