### ISSUE TITLE
Hi got this error how do i solve this?

### ISSUE THREAD

**Issue by hypernewb** [sALTaccount/VAE-BlessUp#2]
![image](https://user-images.githubusercontent.com/19582119/225235134-e7c6add2-e465-460e-a91b-157f3626865c.png)

 --model_type diffusers  --model_path D:\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt --output_path D:\ --output_type diffusers --contrast 1.2 --contrast_operation mul --brightness 0.8 --brightness_operation mul

Tried to launch with these arguments

**Comment by saltacc** [comment]
You are using model_type `diffusers` with a ckpt file. You need to be using `compvis` if you are using the original compvis style checkpoints
